# dataset settings
dataset:
  n_dim: (2,)
  dataset_name: circles
  plot_y_min: -15
  plot_y_max: 15
  plot_x_min: -15
  plot_x_max: 15
  obs_dataset: circle

# model settings
model:
  fwd_drift_file_name: iterative_smoother_circle_forward
  bwd_drift_file_name: iterative_smoother_circle_backward
  score: nn
  drift: nn
  init_drift: nn
  model_type: flat
  warm_start: True
  drift_file_name: iftp_circles_backward_for_filter
  save_score_model: True
  save_drift_model: False
  gamma_min: 0.001
  gamma_max: 1
  init_gamma_multiplier: 1
  load_score_model: False
  init_dist: gauss
  load_drift_model: True

# filter settings
filter:
  n_particles: 1000
  stochastic: False
  t_min: 0
  time_diff: 0.01
  n_steps: 100
  time_forward: True
  transport_eps: 0.01 
  obs_noise: 0.5 #was 0.5
  schedule_type: mult
  obs_noise_1: 0.5
  obs_noise_2: 0.5
  obs_noise_mult: 1.25 
  n_subs: 1
  n_obs: 1 # number of observations 
  n_ts: 10 # number of timeseries to select observations from
  unit_var: False
  zero_mean: False


train:
  lr: 0.001
  n_refresh: 500
  batch_size: 256
  plot: True
  n_iters: 5000
  n_iftp: 6
  n_smooth: 6
  savepickle: True