# training settings
train:
  batch_size : 128 # 128
  nn_iters: 15000 # 5000
  nn_refresh: 1000
  cache_size: 5000  # 300
  iftp_epochs: 12
  lr: 0.0001
  n_trajectories: 1

# dataset settings
dataset:
  n_dim: (1, 28, 28)
  num_channels: 1
  dataset_name: mnist
  data_subset: 8 - eight
  centered: False

# model settings.
model:
  forward_name: iftp_mnist_fwd
  backward_name: iftp_mnist_bwd
  model_output_shift: True
  stepsize_scaling: True
  model_type: imagev2
  start_type: warm
  unit_var: True
  zero_mean: True
  num_steps : 100 # 50 was 100
  time_diff: 0.005  # was 0.005
  gamma_max: 1    # was 1
  gamma_min: 0.0001  # was 10-4
  gamma_type: linear
  num_heads: 4
  fir: False
  nonlinearity: swish
  nf: 64 
  ch_mult: (1, 2, 2)
  num_res_blocks: 3
  attn_resolutions: (14, )
  dropout: 0.0
  resamp_with_conv: True
  skip_rescale: True
  init_scale: 0.0

prior:
  prior_type: match
  prior_model: basic